name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  run-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pwd
          POSTGRES_DB: auth_service
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d auth_service"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgres://postgres:pwd@localhost:5432/auth_service?sslmode=disable

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.26"

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...
